language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install git+https://github.com/Northbreeze/standard_deviation.git
  - pip install -U pytest
# command to run tests
script: pytest
